FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir requests paho-mqtt

COPY server/scripts/data_generator.py .

ENV API_URL=http://server:8000
ENV MQTT_BROKER=mosquitto

CMD ["python", "data_generator.py"]